repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-import-order
          - flake8-quotes

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-python-dateutil
          - types-setuptools

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown, css, scss]
        additional_dependencies:
          - prettier@2.8.8

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: node
        types_or: [javascript, jsx, ts, tsx]
        additional_dependencies:
          - eslint@8.40.0
          - "@typescript-eslint/parser@5.59.6"
          - "@typescript-eslint/eslint-plugin@5.59.6"

      - id: stylelint
        name: stylelint
        entry: npx stylelint --fix
        language: node
        types: [css, scss]
        additional_dependencies:
          - stylelint@15.6.2
          - stylelint-config-standard@33.0.0
          - stylelint-config-standard-scss@9.0.0

      - id: tsc
        name: tsc
        entry: npx tsc --noEmit
        language: node
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false
        additional_dependencies:
          - typescript@5.0.4
