name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: site/frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: site/frontend
        run: npx playwright install --with-deps

      - name: Build application
        working-directory: site/frontend
        run: npm run build

      - name: Run Playwright tests
        working-directory: site/frontend
        run: npm run test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: site/frontend/playwright-report/
          retention-days: 30
